spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:ssgdb
    username: ssg_user
    password:
    sql-script-encoding: utf-8
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        trace: false
        web-allow-others: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 5555
  servlet:
    encoding:
      charset: UTF-8
      enabled: true

eventBus:
  payment:
    threadPool:
      corePool: 5
      maxPool: 10
      queueCapacity: 100